# Generated by Django 5.2.8 on 2026-01-14 00:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='agent',
            old_name='utilisateur',
            new_name='user',
        ),
    ]
