# Generated by Django 5.2.8 on 2026-01-14 01:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0003_alter_agent_user'),
        ('secteurs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='agent',
            name='secteur',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='secteurs.secteur'),
        ),
    ]
