# Generated by Django 5.2.8 on 2026-01-15 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0005_incident'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='agent',
            name='photo_url',
        ),
        migrations.AddField(
            model_name='agent',
            name='photo_profile',
            field=models.ImageField(blank=True, null=True, upload_to='profile/'),
        ),
    ]
