# Generated by Django 5.2.8 on 2026-01-17 20:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0006_remove_agent_photo_url_agent_photo_profile'),
    ]

    operations = [
        migrations.RenameField(
            model_name='incident',
            old_name='created_at',
            new_name='date_signalement',
        ),
    ]
