# Generated by Django 5.2.9 on 2026-05-06 23:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0007_rename_created_at_incident_date_signalement'),
    ]

    operations = [
        migrations.AddField(
            model_name='agent',
            name='salaire_base',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
