# Generated by Django 5.2.9 on 2026-05-06 23:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0008_agent_salaire_base'),
    ]

    operations = [
        migrations.AddField(
            model_name='incident',
            name='notes_gestionnaire',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='incident',
            name='statut',
            field=models.CharField(choices=[('Ouvert', 'Ouvert'), ('En cours', 'En cours'), ('Résolu', 'Résolu'), ('Ignoré', 'Ignoré')], default='Ouvert', max_length=20),
        ),
    ]
