# Generated by Django 5.2.8 on 2026-01-13 14:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Secteur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('code', models.CharField(blank=True, max_length=20, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Rue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=150)),
                ('type_voie', models.CharField(blank=True, choices=[('Rue', 'Rue'), ('Avenue', 'Avenue'), ('Boulevard', 'Boulevard'), ('Allée', 'Allée')], max_length=20, null=True)),
                ('gps_lat', models.DecimalField(blank=True, decimal_places=6, max_digits=10, null=True)),
                ('gps_lon', models.DecimalField(blank=True, decimal_places=6, max_digits=10, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('secteur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rues', to='secteurs.secteur')),
            ],
        ),
    ]
