# Generated by Django 5.2.8 on 2026-01-18 03:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('secteurs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='rue',
            name='code',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
    ]
