# Generated by Django 5.2.8 on 2026-01-18 03:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('secteurs', '0002_rue_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='secteur',
            name='pays',
            field=models.CharField(default='Congo', max_length=100),
        ),
        migrations.AddField(
            model_name='secteur',
            name='ville',
            field=models.CharField(default='Brazzaville', max_length=100),
        ),
    ]
