# Generated by Django 5.2.8 on 2026-01-13 14:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clients', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Echeance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('montant_du', models.DecimalField(decimal_places=2, max_digits=10)),
                ('periode', models.CharField(max_length=7)),
                ('type_echeance', models.CharField(choices=[('Mensuelle', 'Mensuelle'), ('Annuelle', 'Annuelle'), ('Exceptionnelle', 'Exceptionnelle')], max_length=20)),
                ('statut', models.CharField(choices=[('A payer', 'A payer'), ('Payé', 'Payé'), ('En retard', 'En retard')], default='A payer', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='echeances', to='clients.client')),
            ],
        ),
        migrations.CreateModel(
            name='Paiement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('montant_attendu', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('montant_paye', models.DecimalField(decimal_places=2, max_digits=10)),
                ('date_paiement', models.DateTimeField()),
                ('mode_paiement', models.CharField(choices=[('Espèces', 'Espèces'), ('Mobile Money', 'Mobile Money'), ('Virement', 'Virement')], max_length=20)),
                ('reference_transaction', models.CharField(blank=True, max_length=100, null=True)),
                ('statut', models.CharField(choices=[('Validé', 'Validé'), ('Annulé', 'Annulé'), ('Erreur', 'Erreur')], default='Validé', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('echeance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='paiements', to='paiements.echeance')),
                ('utilisateur', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Recu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fichier_url', models.TextField()),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('paiement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recu', to='paiements.paiement')),
            ],
        ),
    ]
