# Generated by Django 5.2.8 on 2026-01-28 01:04

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paiements', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='paiement',
            name='notes',
            field=models.TextField(blank=True, help_text='Commentaires ou référence interne', null=True),
        ),
        migrations.AddField(
            model_name='recu',
            name='numero_recu',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='recu',
            name='signature_comptable',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddIndex(
            model_name='paiement',
            index=models.Index(fields=['date_paiement'], name='paiements_p_date_pa_cc74b5_idx'),
        ),
        migrations.AddIndex(
            model_name='paiement',
            index=models.Index(fields=['mode_paiement'], name='paiements_p_mode_pa_f18e04_idx'),
        ),
        migrations.AddIndex(
            model_name='paiement',
            index=models.Index(fields=['statut'], name='paiements_p_statut_b61122_idx'),
        ),
    ]
