# Generated by Django 5.2.8 on 2026-01-29 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paiements', '0003_alter_paiement_date_paiement_alter_recu_paiement'),
    ]

    operations = [
        migrations.AddField(
            model_name='echeance',
            name='date_echeance',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='paiement',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='recu',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='paiement',
            name='reference_transaction',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='recu',
            name='fichier_url',
            field=models.URLField(),
        ),
    ]
