# Generated by Django 5.2.8 on 2026-02-13 03:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0007_rename_created_at_incident_date_signalement'),
        ('paiements', '0004_echeance_date_echeance_paiement_updated_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='echeance',
            name='periode',
            field=models.CharField(blank=True, max_length=7),
        ),
        migrations.CreateModel(
            name='Salaire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('montant', models.DecimalField(decimal_places=2, max_digits=10)),
                ('periode', models.CharField(max_length=7)),
                ('date_versement', models.DateField()),
                ('statut', models.CharField(choices=[('Prévu', 'Prévu'), ('Payé', 'Payé'), ('En retard', 'En retard')], default='Prévu', max_length=20)),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='salaires', to='agents.agent')),
            ],
        ),
    ]
