# Generated by Django 5.2.8 on 2026-02-13 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paiements', '0005_alter_echeance_periode_salaire'),
    ]

    operations = [
        migrations.AddField(
            model_name='salaire',
            name='prime',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
