# Generated by Django 5.2.8 on 2026-02-13 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paiements', '0006_salaire_prime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salaire',
            name='periode',
            field=models.DateField(),
        ),
    ]
