# Generated by Django 5.2.8 on 2026-02-13 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paiements', '0007_alter_salaire_periode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salaire',
            name='date_versement',
            field=models.DateField(blank=True, null=True),
        ),
    ]
