# Generated by Django 5.2.9 on 2026-05-06 22:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paiements', '0008_alter_salaire_date_versement'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recu',
            name='paiement',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='recus', to='paiements.paiement'),
        ),
    ]
