# Generated by Django 5.2.8 on 2026-01-13 14:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('agents', '0001_initial'),
        ('clients', '0001_initial'),
        ('secteurs', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tournee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('date_planification', models.DateField(blank=True, null=True)),
                ('statut', models.CharField(choices=[('Planifié', 'Planifié'), ('En cours', 'En cours'), ('Terminé', 'Terminé'), ('Annulé', 'Annulé')], default='Planifié', max_length=20)),
                ('heure_debut', models.TimeField(blank=True, null=True)),
                ('heure_fin', models.TimeField(blank=True, null=True)),
                ('vehicule', models.CharField(blank=True, max_length=50, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='agents.agent')),
                ('secteur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='secteurs.secteur')),
            ],
        ),
        migrations.CreateModel(
            name='TourneeClient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heure_passage', models.DateTimeField(blank=True, null=True)),
                ('statut_service', models.CharField(choices=[('Planifié', 'Planifié'), ('Servi', 'Servi'), ('Absent', 'Absent'), ('Problème signalé', 'Problème signalé')], default='Planifié', max_length=30)),
                ('commentaires_agent', models.TextField(blank=True, null=True)),
                ('photo_preuve', models.TextField(blank=True, null=True)),
                ('signature_client', models.TextField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clients.client')),
                ('tournee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clients', to='tournees.tournee')),
            ],
        ),
    ]
