# Generated by Django 5.2.8 on 2026-01-15 19:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0002_alter_client_code_client'),
        ('tournees', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournee',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='clients.client'),
        ),
    ]
