# Generated by Django 5.2.8 on 2026-01-15 19:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tournees', '0002_tournee_client'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tournee',
            name='client',
        ),
    ]
