# Generated by Django 5.2.8 on 2026-01-24 04:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournees', '0003_remove_tournee_client'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tournee',
            name='date_planification',
            field=models.DateField(auto_now_add=True),
        ),
    ]
