# Generated by Django 5.2.9 on 2026-05-06 23:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournees', '0004_alter_tournee_date_planification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tourneeclient',
            name='photo_preuve',
            field=models.ImageField(blank=True, null=True, upload_to='preuves_tournees/'),
        ),
    ]
