# Generated by Django 5.2.8 on 2026-01-13 14:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('abonnements', '0001_initial'),
        ('secteurs', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code_client', models.CharField(max_length=50)),
                ('prenom', models.CharField(blank=True, max_length=100, null=True)),
                ('nom', models.CharField(max_length=100)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('telephone_principal', models.CharField(max_length=20)),
                ('telephone_secondaire', models.CharField(blank=True, max_length=20, null=True)),
                ('adresse_numero', models.CharField(blank=True, max_length=50, null=True)),
                ('montant_mensuel', models.DecimalField(decimal_places=2, max_digits=10)),
                ('date_debut', models.DateField(blank=True, null=True)),
                ('date_recouvrement', models.CharField(choices=[('5', '5'), ('15', '15'), ('30', '30')], max_length=2)),
                ('statut', models.CharField(choices=[('Actif', 'Actif'), ('Suspendu', 'Suspendu'), ('Résilié', 'Résilié')], default='Actif', max_length=20)),
                ('commentaires', models.TextField(blank=True, null=True)),
                ('gps_lat', models.DecimalField(blank=True, decimal_places=6, max_digits=10, null=True)),
                ('gps_lon', models.DecimalField(blank=True, decimal_places=6, max_digits=10, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('abonnement', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='abonnements.abonnement')),
                ('rue', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='clients', to='secteurs.rue')),
            ],
        ),
        migrations.CreateModel(
            name='ClientOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valeur', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='clients.client')),
                ('option', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='abonnements.optionservice')),
            ],
        ),
    ]
