# Generated by Django 5.2.8 on 2026-01-13 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='code_client',
            field=models.CharField(blank=True, max_length=50, unique=True),
        ),
    ]
