# Generated by Django 5.2.8 on 2026-01-28 01:40

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('abonnements', '0002_optionservice_abonnement'),
        ('clients', '0002_alter_client_code_client'),
        ('secteurs', '0003_secteur_pays_secteur_ville'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='client',
            options={'ordering': ['nom', 'prenom'], 'verbose_name': 'Client', 'verbose_name_plural': 'Clients'},
        ),
        migrations.AddField(
            model_name='clientoption',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='date_recouvrement',
            field=models.CharField(choices=[('5', '5'), ('15', '15'), ('30', '30')], help_text='Jour du mois où le recouvrement est prévu', max_length=2),
        ),
        migrations.AlterField(
            model_name='client',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, validators=[django.core.validators.EmailValidator(message='Veuillez entrer un email valide')]),
        ),
        migrations.AlterField(
            model_name='client',
            name='telephone_principal',
            field=models.CharField(max_length=20, validators=[django.core.validators.RegexValidator(message='Numéro de téléphone invalide', regex='^\\+?\\d{9,15}$')]),
        ),
        migrations.AlterField(
            model_name='client',
            name='telephone_secondaire',
            field=models.CharField(blank=True, max_length=20, null=True, validators=[django.core.validators.RegexValidator(message='Numéro de téléphone invalide', regex='^\\+?\\d{9,15}$')]),
        ),
        migrations.AddIndex(
            model_name='client',
            index=models.Index(fields=['code_client'], name='clients_cli_code_cl_45c6a2_idx'),
        ),
        migrations.AddIndex(
            model_name='client',
            index=models.Index(fields=['statut'], name='clients_cli_statut_d69dca_idx'),
        ),
        migrations.AddIndex(
            model_name='client',
            index=models.Index(fields=['rue'], name='clients_cli_rue_id_df62a8_idx'),
        ),
        migrations.AddIndex(
            model_name='client',
            index=models.Index(fields=['abonnement'], name='clients_cli_abonnem_5154c4_idx'),
        ),
    ]
