# Generated by Django 5.2.8 on 2026-02-01 11:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('abonnements', '0002_optionservice_abonnement'),
        ('clients', '0003_alter_client_options_clientoption_updated_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='abonnement',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='clients', to='abonnements.abonnement'),
        ),
    ]
