# Generated by Django 5.2.8 on 2026-02-06 02:17

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0004_alter_client_abonnement'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='date_recouvrement',
            field=models.PositiveSmallIntegerField(help_text='Jour du mois où le recouvrement est prévu (1 à 31)', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(31)]),
        ),
    ]
