# Generated by Django 5.2.8 on 2026-02-08 02:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0005_alter_client_date_recouvrement'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='montant_mensuel',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True),
        ),
    ]
