# Generated by Django 5.2.8 on 2026-02-08 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0006_alter_client_montant_mensuel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='date_recouvrement',
            field=models.DateField(help_text='Date exacte du premier recouvrement'),
        ),
    ]
