# Generated by Django 5.2.8 on 2026-05-20 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0007_alter_client_date_recouvrement'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='code_client',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
    ]
