# Generated by Django 5.2.8 on 2026-01-25 15:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('abonnements', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='optionservice',
            name='abonnement',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='options', to='abonnements.abonnement'),
        ),
    ]
